### ISSUE TITLE
Create a logo for DevOps community 

### ISSUE THREAD

**Issue by rohitg00** [rohitg00/DevOpsCommunity#10]
Submit logos for the review.
Whichever, Community loves the most will be set as official logo for DevOps Community.
I want to open-source everything from community side, This is your chance to contribute.

Note: Create logo from scratch, Don't use copyright or template images.

**Comment by cosmicqbit** [comment]
Here is the illustration. I will share the original files / deliverables if the logo is selected.

![default](https://user-images.githubusercontent.com/75565639/190205533-f8218e66-876a-466c-b884-e7c69ce6ec0f.png)

---

<img width="807" alt="image" src="https://user-images.githubusercontent.com/75565639/190205682-c28debf1-7036-4897-85ab-5e54e9e8a60b.png">

---

**Comment by rohitg00** [comment]
Submit the PR for this @cosmicqbit

**Comment by cosmicqbit** [comment]
Shall I include original files of the logo in PR in a separate folder! I mean I can deliver the files via cloud link if that is okay.

**Comment by rohitg00** [comment]
Yes, Please.

**Comment by cosmicqbit** [comment]
Alright, here is the [download link](https://app.blackhole.run/#d1d044d0c21DPobqmdKMY1YwWHRqhiaD1HwH3x9u8pwR).

**Comment by cosmicqbit** [comment]
Can you please look into the PR & merge it. I wanted to contribute to Readme next.

**Comment by rohitg00** [comment]
Thank you, Issue closed
