### ISSUE TITLE
[Docs]: Add issue template

### ISSUE THREAD

**Issue by SuperAayush** [rohitg00/DevOpsCommunity#27]
In order to correctly structure the issue created and make it easy for the maintainer of the repo to look into what the issue is, it is recommended to make an issue template.
Refer to this page for creating an issue template: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by SuperAayush** [comment]
Yes please work on it 😄!!

**Comment by rohitg00** [comment]
@SuperAayush Please review - Issue template.
