### ISSUE TITLE
[Docs]: Add pull request template

### ISSUE THREAD

**Issue by SuperAayush** [rohitg00/DevOpsCommunity#28]
When you add a pull request template to your repository, project contributors will automatically see the template's contents in the pull request body.

For more information read this documentation -> https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by KlausMikhaelson** [comment]
Hey @SuperAayush if no one is working on it so can I take this issue ?

**Comment by SuperAayush** [comment]
Yes @KlausMikhaelson you can work on it!!

**Comment by rohitg00** [comment]
@SuperAayush , Please review this - KlausMikhaelson:patch-1 #30
