### ISSUE TITLE
Add Civo Logo and Hosting details

### ISSUE THREAD

**Issue by rohitg00** [rohitg00/DevOpsCommunity#39]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yntpdotme** [comment]
Hey @rohitg00,

Checkout this PR https://github.com/rohitg00/RC4Community/pull/29

**Comment by rohitg00** [comment]
Thanks for the PR, It's merged.
